"""create energy forecasts and deployment recommendations

Revision ID: 1d28e764d83d
Revises: 000000000003
Create Date: 2026-07-26 10:59:25.609933

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1d28e764d83d'
down_revision = '000000000003'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ranked_site_ids', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_deployment_recommendations_id'), 'deployment_recommendations', ['id'], unique=False)
    op.create_table('energy_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('solar_seasonal_kwh', sa.JSON(), nullable=True),
    sa.Column('wind_seasonal_kwh', sa.JSON(), nullable=True),
    sa.Column('solar_longterm_kwh', sa.JSON(), nullable=True),
    sa.Column('wind_longterm_kwh', sa.JSON(), nullable=True),
    sa.Column('solar_annual_revenue', sa.Float(), nullable=True),
    sa.Column('wind_annual_revenue', sa.Float(), nullable=True),
    sa.Column('combined_annual_revenue', sa.Float(), nullable=True),
    sa.Column('electricity_rate_usd_kwh', sa.Float(), nullable=True),
    sa.Column('grid_contribution_ratio', sa.Float(), nullable=True),
    sa.Column('grid_contribution_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_index(op.f('ix_energy_forecasts_id'), 'energy_forecasts', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_forecasts_id'), table_name='energy_forecasts')
    op.drop_table('energy_forecasts')
    op.drop_index(op.f('ix_deployment_recommendations_id'), table_name='deployment_recommendations')
    op.drop_table('deployment_recommendations')
    # ### end Alembic commands ###
